//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Proba2
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Вакант должн.
    /// </summary>
    // *** Start programmer edit section *** (ВакантДолжн CustomAttributes)

    // *** End programmer edit section *** (ВакантДолжн CustomAttributes)
    [AutoAltered()]
    [Caption("Вакант должн")]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("ВакантДолжнE", new string[] {
            "IDДолжности as \'I d должности\'",
            "Должность as \'Должность\'"})]
    [View("ВакантДолжнL", new string[] {
            "IDДолжности as \'I d должности\'",
            "Должность as \'Должность\'"})]
    public class ВакантДолжн : ICSSoft.STORMNET.DataObject
    {
        
        private int fIDДолжности;
        
        private string fДолжность;
        
        // *** Start programmer edit section *** (ВакантДолжн CustomMembers)

        // *** End programmer edit section *** (ВакантДолжн CustomMembers)

        
        /// <summary>
        /// IDДолжности.
        /// </summary>
        // *** Start programmer edit section *** (ВакантДолжн.IDДолжности CustomAttributes)

        // *** End programmer edit section *** (ВакантДолжн.IDДолжности CustomAttributes)
        public virtual int IDДолжности
        {
            get
            {
                // *** Start programmer edit section *** (ВакантДолжн.IDДолжности Get start)

                // *** End programmer edit section *** (ВакантДолжн.IDДолжности Get start)
                int result = this.fIDДолжности;
                // *** Start programmer edit section *** (ВакантДолжн.IDДолжности Get end)

                // *** End programmer edit section *** (ВакантДолжн.IDДолжности Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ВакантДолжн.IDДолжности Set start)

                // *** End programmer edit section *** (ВакантДолжн.IDДолжности Set start)
                this.fIDДолжности = value;
                // *** Start programmer edit section *** (ВакантДолжн.IDДолжности Set end)

                // *** End programmer edit section *** (ВакантДолжн.IDДолжности Set end)
            }
        }
        
        /// <summary>
        /// Должность.
        /// </summary>
        // *** Start programmer edit section *** (ВакантДолжн.Должность CustomAttributes)

        // *** End programmer edit section *** (ВакантДолжн.Должность CustomAttributes)
        [StrLen(255)]
        public virtual string Должность
        {
            get
            {
                // *** Start programmer edit section *** (ВакантДолжн.Должность Get start)

                // *** End programmer edit section *** (ВакантДолжн.Должность Get start)
                string result = this.fДолжность;
                // *** Start programmer edit section *** (ВакантДолжн.Должность Get end)

                // *** End programmer edit section *** (ВакантДолжн.Должность Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ВакантДолжн.Должность Set start)

                // *** End programmer edit section *** (ВакантДолжн.Должность Set start)
                this.fДолжность = value;
                // *** Start programmer edit section *** (ВакантДолжн.Должность Set end)

                // *** End programmer edit section *** (ВакантДолжн.Должность Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "ВакантДолжнE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ВакантДолжнE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ВакантДолжнE", typeof(IIS.Proba2.ВакантДолжн));
                }
            }
            
            /// <summary>
            /// "ВакантДолжнL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ВакантДолжнL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ВакантДолжнL", typeof(IIS.Proba2.ВакантДолжн));
                }
            }
        }
    }
}
