//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Proba2
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Итог собесед.
    /// </summary>
    // *** Start programmer edit section *** (ИтогСобесед CustomAttributes)

    // *** End programmer edit section *** (ИтогСобесед CustomAttributes)
    public enum ИтогСобесед
    {
        
        // *** Start programmer edit section *** (ИтогСобесед.ПриглНаРаб CustomAttributes)

        // *** End programmer edit section *** (ИтогСобесед.ПриглНаРаб CustomAttributes)
        [Caption("ПриглНаРаб")]
        ПриглНаРаб,
        
        // *** Start programmer edit section *** (ИтогСобесед.ОтклонКандид CustomAttributes)

        // *** End programmer edit section *** (ИтогСобесед.ОтклонКандид CustomAttributes)
        [Caption("ОтклонКандид")]
        ОтклонКандид,
        
        // *** Start programmer edit section *** (ИтогСобесед.НаРассмотр CustomAttributes)

        // *** End programmer edit section *** (ИтогСобесед.НаРассмотр CustomAttributes)
        [Caption("НаРассмотр")]
        НаРассмотр,
    }
}
