//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Proba2
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Рег результ.
    /// </summary>
    // *** Start programmer edit section *** (РегРезульт CustomAttributes)

    // *** End programmer edit section *** (РегРезульт CustomAttributes)
    [AutoAltered()]
    [Caption("Рег результ")]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("РегРезультE", new string[] {
            "ДатРегРезСобес as \'Дат рег рез собес\'",
            "ПриглНаРаб as \'Пригл на раб\'",
            "КандидОтклон as \'Кандид отклон\'",
            "Организация as \'Организация\'",
            "Организация.Наименование as \'Наименование\'",
            "ПланирСобес as \'Время\'",
            "ПланирСобес.ИметьПриСебе as \'Иметь при себе\'",
            "ПланирСобес.РегистАнкеты.ФИОКандид as \'ФИО\'",
            "ПланирСобес.РегистАнкеты.ВакантДолжн.Должность as \'Вакантная должность\'"}, Hidden=new string[] {
            "Организация.Наименование",
            "ПланирСобес.ИметьПриСебе"})]
    [AssociatedDetailViewAttribute("РегРезультE", "ТЧРегРезульт", "ТЧРегРезультE", true, "", "Т ч рег результ", true, new string[] {
            ""})]
    [MasterViewDefineAttribute("РегРезультE", "Организация", ICSSoft.STORMNET.LookupTypeEnum.Standard, "", "Наименование")]
    [MasterViewDefineAttribute("РегРезультE", "ПланирСобес", ICSSoft.STORMNET.LookupTypeEnum.Standard, "", "Время")]
    [View("РегРезультL", new string[] {
            "ДатРегРезСобес as \'Дат рег рез собес\'",
            "ПриглНаРаб as \'Пригл на раб\'",
            "КандидОтклон as \'Кандид отклон\'",
            "Организация.Наименование as \'Наименование\'",
            "ПланирСобес.РегистАнкеты.ФИОКандид as \'ФИО\'",
            "ПланирСобес.РегистАнкеты.ВакантДолжн.Должность as \'Вакантная должность\'",
            "ПланирСобес.ИметьПриСебе as \'Время\'"})]
    public class РегРезульт : ICSSoft.STORMNET.DataObject
    {
        
        private System.DateTime fДатРегРезСобес;
        
        private bool fПриглНаРаб;
        
        private bool fКандидОтклон;
        
        private IIS.Proba2.Организация fОрганизация;
        
        private IIS.Proba2.ПланирСобес fПланирСобес;
        
        private IIS.Proba2.DetailArrayOfТЧРегРезульт fТЧРегРезульт;
        
        // *** Start programmer edit section *** (РегРезульт CustomMembers)

        // *** End programmer edit section *** (РегРезульт CustomMembers)

        
        /// <summary>
        /// ДатРегРезСобес.
        /// </summary>
        // *** Start programmer edit section *** (РегРезульт.ДатРегРезСобес CustomAttributes)

        // *** End programmer edit section *** (РегРезульт.ДатРегРезСобес CustomAttributes)
        public virtual System.DateTime ДатРегРезСобес
        {
            get
            {
                // *** Start programmer edit section *** (РегРезульт.ДатРегРезСобес Get start)

                // *** End programmer edit section *** (РегРезульт.ДатРегРезСобес Get start)
                System.DateTime result = this.fДатРегРезСобес;
                // *** Start programmer edit section *** (РегРезульт.ДатРегРезСобес Get end)

                // *** End programmer edit section *** (РегРезульт.ДатРегРезСобес Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (РегРезульт.ДатРегРезСобес Set start)

                // *** End programmer edit section *** (РегРезульт.ДатРегРезСобес Set start)
                this.fДатРегРезСобес = value;
                // *** Start programmer edit section *** (РегРезульт.ДатРегРезСобес Set end)

                // *** End programmer edit section *** (РегРезульт.ДатРегРезСобес Set end)
            }
        }
        
        /// <summary>
        /// КандидОтклон.
        /// </summary>
        // *** Start programmer edit section *** (РегРезульт.КандидОтклон CustomAttributes)

        // *** End programmer edit section *** (РегРезульт.КандидОтклон CustomAttributes)
        public virtual bool КандидОтклон
        {
            get
            {
                // *** Start programmer edit section *** (РегРезульт.КандидОтклон Get start)

                // *** End programmer edit section *** (РегРезульт.КандидОтклон Get start)
                bool result = this.fКандидОтклон;
                // *** Start programmer edit section *** (РегРезульт.КандидОтклон Get end)

                // *** End programmer edit section *** (РегРезульт.КандидОтклон Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (РегРезульт.КандидОтклон Set start)

                // *** End programmer edit section *** (РегРезульт.КандидОтклон Set start)
                this.fКандидОтклон = value;
                // *** Start programmer edit section *** (РегРезульт.КандидОтклон Set end)

                // *** End programmer edit section *** (РегРезульт.КандидОтклон Set end)
            }
        }
        
        /// <summary>
        /// ПриглНаРаб.
        /// </summary>
        // *** Start programmer edit section *** (РегРезульт.ПриглНаРаб CustomAttributes)

        // *** End programmer edit section *** (РегРезульт.ПриглНаРаб CustomAttributes)
        public virtual bool ПриглНаРаб
        {
            get
            {
                // *** Start programmer edit section *** (РегРезульт.ПриглНаРаб Get start)

                // *** End programmer edit section *** (РегРезульт.ПриглНаРаб Get start)
                bool result = this.fПриглНаРаб;
                // *** Start programmer edit section *** (РегРезульт.ПриглНаРаб Get end)

                // *** End programmer edit section *** (РегРезульт.ПриглНаРаб Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (РегРезульт.ПриглНаРаб Set start)

                // *** End programmer edit section *** (РегРезульт.ПриглНаРаб Set start)
                this.fПриглНаРаб = value;
                // *** Start programmer edit section *** (РегРезульт.ПриглНаРаб Set end)

                // *** End programmer edit section *** (РегРезульт.ПриглНаРаб Set end)
            }
        }
        
        /// <summary>
        /// Рег результ.
        /// </summary>
        // *** Start programmer edit section *** (РегРезульт.Организация CustomAttributes)

        // *** End programmer edit section *** (РегРезульт.Организация CustomAttributes)
        [PropertyStorage(new string[] {
                "Организация"})]
        [NotNull()]
        public virtual IIS.Proba2.Организация Организация
        {
            get
            {
                // *** Start programmer edit section *** (РегРезульт.Организация Get start)

                // *** End programmer edit section *** (РегРезульт.Организация Get start)
                IIS.Proba2.Организация result = this.fОрганизация;
                // *** Start programmer edit section *** (РегРезульт.Организация Get end)

                // *** End programmer edit section *** (РегРезульт.Организация Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (РегРезульт.Организация Set start)

                // *** End programmer edit section *** (РегРезульт.Организация Set start)
                this.fОрганизация = value;
                // *** Start programmer edit section *** (РегРезульт.Организация Set end)

                // *** End programmer edit section *** (РегРезульт.Организация Set end)
            }
        }
        
        /// <summary>
        /// Рег результ.
        /// </summary>
        // *** Start programmer edit section *** (РегРезульт.ПланирСобес CustomAttributes)

        // *** End programmer edit section *** (РегРезульт.ПланирСобес CustomAttributes)
        [PropertyStorage(new string[] {
                "ПланирСобес"})]
        [NotNull()]
        public virtual IIS.Proba2.ПланирСобес ПланирСобес
        {
            get
            {
                // *** Start programmer edit section *** (РегРезульт.ПланирСобес Get start)

                // *** End programmer edit section *** (РегРезульт.ПланирСобес Get start)
                IIS.Proba2.ПланирСобес result = this.fПланирСобес;
                // *** Start programmer edit section *** (РегРезульт.ПланирСобес Get end)

                // *** End programmer edit section *** (РегРезульт.ПланирСобес Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (РегРезульт.ПланирСобес Set start)

                // *** End programmer edit section *** (РегРезульт.ПланирСобес Set start)
                this.fПланирСобес = value;
                // *** Start programmer edit section *** (РегРезульт.ПланирСобес Set end)

                // *** End programmer edit section *** (РегРезульт.ПланирСобес Set end)
            }
        }
        
        /// <summary>
        /// Рег результ.
        /// </summary>
        // *** Start programmer edit section *** (РегРезульт.ТЧРегРезульт CustomAttributes)

        // *** End programmer edit section *** (РегРезульт.ТЧРегРезульт CustomAttributes)
        public virtual IIS.Proba2.DetailArrayOfТЧРегРезульт ТЧРегРезульт
        {
            get
            {
                // *** Start programmer edit section *** (РегРезульт.ТЧРегРезульт Get start)

                // *** End programmer edit section *** (РегРезульт.ТЧРегРезульт Get start)
                if ((this.fТЧРегРезульт == null))
                {
                    this.fТЧРегРезульт = new IIS.Proba2.DetailArrayOfТЧРегРезульт(this);
                }
                IIS.Proba2.DetailArrayOfТЧРегРезульт result = this.fТЧРегРезульт;
                // *** Start programmer edit section *** (РегРезульт.ТЧРегРезульт Get end)

                // *** End programmer edit section *** (РегРезульт.ТЧРегРезульт Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (РегРезульт.ТЧРегРезульт Set start)

                // *** End programmer edit section *** (РегРезульт.ТЧРегРезульт Set start)
                this.fТЧРегРезульт = value;
                // *** Start programmer edit section *** (РегРезульт.ТЧРегРезульт Set end)

                // *** End programmer edit section *** (РегРезульт.ТЧРегРезульт Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "РегРезультE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View РегРезультE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("РегРезультE", typeof(IIS.Proba2.РегРезульт));
                }
            }
            
            /// <summary>
            /// "РегРезультL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View РегРезультL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("РегРезультL", typeof(IIS.Proba2.РегРезульт));
                }
            }
        }
    }
}
