//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Proba2
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Сотруд.
    /// </summary>
    // *** Start programmer edit section *** (Сотруд CustomAttributes)

    // *** End programmer edit section *** (Сотруд CustomAttributes)
    [AutoAltered()]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("СотрудE", new string[0])]
    [View("СотрудL", new string[0])]
    public class Сотруд : ICSSoft.STORMNET.DataObject
    {
        
        // *** Start programmer edit section *** (Сотруд CustomMembers)

        // *** End programmer edit section *** (Сотруд CustomMembers)

        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "СотрудE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View СотрудE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("СотрудE", typeof(IIS.Proba2.Сотруд));
                }
            }
            
            /// <summary>
            /// "СотрудL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View СотрудL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("СотрудL", typeof(IIS.Proba2.Сотруд));
                }
            }
        }
    }
}
