//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Proba2
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Т ч граф собес.
    /// </summary>
    // *** Start programmer edit section *** (ТЧГрафСобес CustomAttributes)

    // *** End programmer edit section *** (ТЧГрафСобес CustomAttributes)
    [AutoAltered()]
    [Caption("Т ч граф собес")]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("ТЧГрафСобесE", new string[] {
            "ПланирСобес as \'Дата план собес\'",
            "ПланирСобес.Время as \'Время\'",
            "ПланирСобес.ИметьПриСебе as \'Иметь при себе\'",
            "ПланирСобес.РегистАнкеты.ФИОКандид as \'ФИО\'",
            "ПланирСобес.РегистАнкеты.ВакантДолжн.Должность as \'Вакантная должность\'"}, Hidden=new string[] {
            "ПланирСобес.ИметьПриСебе"})]
    [MasterViewDefineAttribute("ТЧГрафСобесE", "ПланирСобес", ICSSoft.STORMNET.LookupTypeEnum.Standard, "", "ДатаПланСобес")]
    public class ТЧГрафСобес : ICSSoft.STORMNET.DataObject
    {
        
        private IIS.Proba2.ПланирСобес fПланирСобес;
        
        private IIS.Proba2.ГрафСобес fГрафСобес;
        
        // *** Start programmer edit section *** (ТЧГрафСобес CustomMembers)

        // *** End programmer edit section *** (ТЧГрафСобес CustomMembers)

        
        /// <summary>
        /// Т ч граф собес.
        /// </summary>
        // *** Start programmer edit section *** (ТЧГрафСобес.ПланирСобес CustomAttributes)

        // *** End programmer edit section *** (ТЧГрафСобес.ПланирСобес CustomAttributes)
        [PropertyStorage(new string[] {
                "ПланирСобес"})]
        [NotNull()]
        public virtual IIS.Proba2.ПланирСобес ПланирСобес
        {
            get
            {
                // *** Start programmer edit section *** (ТЧГрафСобес.ПланирСобес Get start)

                // *** End programmer edit section *** (ТЧГрафСобес.ПланирСобес Get start)
                IIS.Proba2.ПланирСобес result = this.fПланирСобес;
                // *** Start programmer edit section *** (ТЧГрафСобес.ПланирСобес Get end)

                // *** End programmer edit section *** (ТЧГрафСобес.ПланирСобес Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ТЧГрафСобес.ПланирСобес Set start)

                // *** End programmer edit section *** (ТЧГрафСобес.ПланирСобес Set start)
                this.fПланирСобес = value;
                // *** Start programmer edit section *** (ТЧГрафСобес.ПланирСобес Set end)

                // *** End programmer edit section *** (ТЧГрафСобес.ПланирСобес Set end)
            }
        }
        
        /// <summary>
        /// мастеровая ссылка на шапку IIS.Proba2.ГрафСобес.
        /// </summary>
        // *** Start programmer edit section *** (ТЧГрафСобес.ГрафСобес CustomAttributes)

        // *** End programmer edit section *** (ТЧГрафСобес.ГрафСобес CustomAttributes)
        [Agregator()]
        [NotNull()]
        [PropertyStorage(new string[] {
                "ГрафСобес"})]
        public virtual IIS.Proba2.ГрафСобес ГрафСобес
        {
            get
            {
                // *** Start programmer edit section *** (ТЧГрафСобес.ГрафСобес Get start)

                // *** End programmer edit section *** (ТЧГрафСобес.ГрафСобес Get start)
                IIS.Proba2.ГрафСобес result = this.fГрафСобес;
                // *** Start programmer edit section *** (ТЧГрафСобес.ГрафСобес Get end)

                // *** End programmer edit section *** (ТЧГрафСобес.ГрафСобес Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ТЧГрафСобес.ГрафСобес Set start)

                // *** End programmer edit section *** (ТЧГрафСобес.ГрафСобес Set start)
                this.fГрафСобес = value;
                // *** Start programmer edit section *** (ТЧГрафСобес.ГрафСобес Set end)

                // *** End programmer edit section *** (ТЧГрафСобес.ГрафСобес Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "ТЧГрафСобесE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ТЧГрафСобесE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ТЧГрафСобесE", typeof(IIS.Proba2.ТЧГрафСобес));
                }
            }
        }
    }
    
    /// <summary>
    /// Detail array of ТЧГрафСобес.
    /// </summary>
    // *** Start programmer edit section *** (DetailArrayDetailArrayOfТЧГрафСобес CustomAttributes)

    // *** End programmer edit section *** (DetailArrayDetailArrayOfТЧГрафСобес CustomAttributes)
    public class DetailArrayOfТЧГрафСобес : ICSSoft.STORMNET.DetailArray
    {
        
        // *** Start programmer edit section *** (IIS.Proba2.DetailArrayOfТЧГрафСобес members)

        // *** End programmer edit section *** (IIS.Proba2.DetailArrayOfТЧГрафСобес members)

        
        /// <summary>
        /// Construct detail array.
        /// </summary>
        /// <summary>
        /// Returns object with type ТЧГрафСобес by index.
        /// </summary>
        /// <summary>
        /// Adds object with type ТЧГрафСобес.
        /// </summary>
        public DetailArrayOfТЧГрафСобес(IIS.Proba2.ГрафСобес fГрафСобес) : 
                base(typeof(ТЧГрафСобес), ((ICSSoft.STORMNET.DataObject)(fГрафСобес)))
        {
        }
        
        public IIS.Proba2.ТЧГрафСобес this[int index]
        {
            get
            {
                return ((IIS.Proba2.ТЧГрафСобес)(this.ItemByIndex(index)));
            }
        }
        
        public virtual void Add(IIS.Proba2.ТЧГрафСобес dataobject)
        {
            this.AddObject(((ICSSoft.STORMNET.DataObject)(dataobject)));
        }
    }
}
